<?php
#####################################################################################################
# SXVLink Config Class
#####################################################################################################

class SVXLink {

    private $settingsArray;
    private $portsArray;
	private $modulesArray;
	private $modulesListArray;
	private $orpFileHeader;
    private $web_path = '/var/www/openrepeater/';	

	public function __construct($settingsArray, $portsArray, $modulesArray) {
		$this->settingsArray = $settingsArray;
		$this->portsArray = $portsArray;
		$this->modulesArray = $modulesArray;
		
		$orpFileHeader = '
		###############################################################################
		#
		#  OPENREPEATER / SVXLINK CONFIGURATION FILE
		#  This file was auto generated by OpenRepeater. 
		#  DO NOT MAKE CHANGES IN THIS FILE AS THEY WILL BE OVERWRITTEN
		#
		###############################################################################';
		#Clean up tabs/white spaces
		$this->orpFileHeader = trim(preg_replace('/\t+/', '', $orpFileHeader)) . "\n\n";
		
	}


	###############################################
	# Build Module Config Files
	###############################################

	public function build_module_list() {

		$this->write_module_configs();

		// Build Module List from Array
		if(!empty($this->modulesListArray)) {
			return array( 'MODULES' => implode(",", $this->modulesListArray) );
		} else {
			return array( '#MODULES' => 'NONE' );
		}

	}


	public function write_module_configs() {
		$this->modulesListArray = array();
		foreach($this->modulesArray as $cur_mod) { 
			if ($cur_mod['moduleEnabled']==1) {
				$module_config_array = array();
				
				// Add Module name to array to output list in logic section
				$this->modulesListArray[] = 'Module'.$cur_mod['svxlinkName'];
						
				// Build Module Configuration
				$mod_build_file = $this->web_path . 'modules/' . $cur_mod['svxlinkName'] . '/build_config.php';
				if (file_exists($mod_build_file)) {
					// Module has a build file...use it.
					include($mod_build_file);
		
				} else {
					// Module doesn't have a build file so create minimal configuration
					$module_config_array['Module'.$cur_mod['svxlinkName']] = [
						'NAME' => $cur_mod['svxlinkName'],
						'ID' => $cur_mod['svxlinkID'],
						'TIMEOUT' => '60',				
					];
				}
								
				// Write out Module Config File for SVXLink
				$this->write_config($module_config_array, 'Module'.$cur_mod['svxlinkName'].'.conf', 'ini');
		
			} 
		}
	}
	
	
	
	###############################################
	# Build Global Section
	###############################################

	public function build_global($logics) {
		if (is_array($logics)) { $logics = implode(",", $logics); } // Convert array to CSV.
		
		$global_array['MODULE_PATH'] = '/usr/lib/arm-linux-gnueabihf/svxlink';
		$global_array['LOGICS'] = $logics;
		$global_array['CFG_DIR'] = 'svxlink.d';
		$global_array['TIMESTAMP_FORMAT'] = '"%c"';
		$global_array['CARD_SAMPLE_RATE'] = '16000';
		//$global_array['LOCATION_INFO'] = 'LocationInfo';
		//$global_array['LINKS'] = 'LinkToR4';
		
		return $global_array;
	}
	
	
	
	###############################################
	# Build RX Port
	###############################################

	public function build_rx($curPort) {
		$audio_dev = explode("|", $this->portsArray[$curPort]['rxAudioDev']);
		
		$rx_array['Rx'.$curPort] = [
			'TYPE' => 'Local',
			'AUDIO_DEV' => $audio_dev[0],
			'AUDIO_CHANNEL' => $audio_dev[1],
		];
	
		if (strtolower($portsArray[$curPort]['rxMode']) == 'vox') {
			// VOX Squelch Mode
			$rx_array['Rx'.$curPort] += [
				'SQL_DET' => 'VOX',
				'VOX_FILTER_DEPTH' => '150',
				'VOX_THRESH' => '300',
				'SQL_HANGTIME' => '1000',
			];
	
		} else {
			// COS Squelch Mode
			$rx_array['Rx'.$curPort] += [
				'SQL_DET' => 'GPIO',
				'GPIO_SQL_PIN' => 'gpio' . $this->portsArray[$curPort]['rxGPIO'],
				'SQL_HANGTIME' => '10',
			];
		}
	
		$rx_array['Rx'.$curPort] += [
			'SQL_START_DELAY' => '1',
			'SQL_DELAY' => '10',
			'SIGLEV_SLOPE' => '1',
			'SIGLEV_OFFSET' => '0',
			'SIGLEV_OPEN_THRESH' => '30',
			'SIGLEV_CLOSE_THRESH' => '10',
			'DEEMPHASIS' => '1',
			'PEAK_METER' => '0',
			'DTMF_DEC_TYPE' => 'INTERNAL',
			'DTMF_MUTING' => '1',
			'DTMF_HANGTIME' => '100',
			'DTMF_SERIAL' => '/dev/ttyS0',
		];
	
		return $rx_array;
	}



	###############################################
	# Build TX Port
	###############################################

	public function build_tx($curPort) {
		$audio_dev = explode("|", $this->portsArray[$curPort]['txAudioDev']);
	
		$tx_array['Tx'.$curPort] = [
			'TYPE' => 'Local',
			'AUDIO_DEV' => $audio_dev[0],
			'AUDIO_CHANNEL' => $audio_dev[1],
			'PTT_TYPE' => 'GPIO',
			'PTT_PORT' => 'GPIO',
			'PTT_PIN' => 'gpio'.$this->portsArray[$curPort]['txGPIO'],
			'PTT_HANGTIME' => ($this->settingsArray['txTailValueSec'] * 1000),
			'TIMEOUT' => '300',
			'TX_DELAY' => '500',
		];
	
		if ($this->settingsArray['txTone']) {
			$tx_array['Tx'.$curPort] += [
				'CTCSS_FQ' => $this->settingsArray['txTone'],
				'CTCSS_LEVEL' => '9',
			];
		}
	
		$tx_array['Tx'.$curPort] += [
			'PREEMPHASIS' => '0',
			'DTMF_TONE_LENGTH' => '100',
			'DTMF_TONE_SPACING' => '50',
			'DTMF_TONE_PWR' => '-18',
		];
	
		return $tx_array;
	}



	###############################################
	# Build INI Format
	###############################################

	public function build_ini($input_array) {
		$section_separator = '###############################################################################';
		
		$ini_return = "";
		$section_count = 0;
		foreach($input_array as $ini_section => $ini_section_array) {
			$section_count++;
			if ($section_count > 1) { $ini_return .= $section_separator . "\n\n";}
		    $ini_return .= "[" . $ini_section . "]\n";
			foreach($ini_section_array as $key => $value) {
				$ini_return .= $key . "=" . $value . "\n";
			}
		    $ini_return .= "\n";
		}
	
		return $ini_return;
	}



	###############################################
	# Write Config File
	###############################################

	public function write_config($data, $filename, $format = 'text') {
		
		if ($format == 'ini') {
			$data = $this->build_ini($data); // Convert Array to INI format
		}
		$file_output = $this->orpFileHeader . $data;


		switch ($filename) {
		    case "svxlink.conf":
				$filepath = '/etc/openrepeater/svxlink/' . $filename;
		        break;
		    case "gpio.conf":
				$filepath = '/etc/openrepeater/svxlink/' . $filename;
		        break;
		    case "CustomLogic.tcl":
				$filepath = '/etc/openrepeater/svxlink/local-events.d/' . $filename;
		        break;
		    case (strpos($filename, "Module") === 0): // Begins with Module
				$filepath = '/etc/openrepeater/svxlink/svxlink.d/' . $filename;
		        break;
		}

		file_put_contents($filepath, $file_output );
	}





}
?>