#!/bin/bash
SERVICE=svxlink

ps -u $SERVICE | grep -v grep | grep $SERVICE > /dev/null
result=$?
echo "exit code: ${result}"
if [ "${result}" -eq "0" ] ; then
    echo "$(date): $SERVICE service running, all is fine"
else
    echo "$(date): $SERVICE is not running"
    echo "$(date): Atempting to start svxlink"
    sudo systemctl enable svxlink.service
    sudo service svxlink start
fi
