#!/bin/bash
# Copyright ©2017 OpenRepeater Project - Aaron Crawford, N3MBH & Richard Neese KB3VGW
# Licended under GPL v2 or later

# This is a helper script for OpenRepeater. This script is primarily intended
# to extend the functionality of the of the ORP web user interface and allow it
# to execute specific system commands that it would not normally be able to
# perform due to security reasons in Linux. DO NOT INCLUDE commands in this
# script that a potential hacker could utilize to compromise the system if the
# web server were to be compromised. This script should be a delicate balance
# between needed functionality in the web interface and security. 

# NOTE: NO NEED TO PREFIX COMMANDS WITH SUDO AS THIS SCRIPT IS INTENDED TO BE RUN AS ROOT USING SUDO COMMAND

####### WORK IN PROGRESS........

###############################################################################
# DEFINE FUNCTIONS
###############################################################################

### SVXLINK FUNCTIONS ###
function display_help {
	echo "OPEN REPEATER HELPER"
	echo "This is a helper script for OpenRepeater. This script is primarily intended"
	echo "to extend the functionality of the of the ORP web user interface and allow it"
	echo "to execute specific system commands that it would not normally be able to"
	echo "perform due to security reasons in Linux."
	echo ""
	echo "USAGE: orp_helper [service] [option]"
}

function svxlink_disable {
	echo "SVXLink Disable"
	service svxlink stop
	systemctl disable svxlink.service
}

function svxlink_enable {
	echo "SVXLink Enable"
	systemctl enable svxlink.service
	service svxlink start
}

function svxlink_restart {
	service svxlink restart
	svxlink_status
}

function svxlink_stop {
	service svxlink stop
	svxlink_status
}

function svxlink_start {
	service svxlink start
	svxlink_status
}

function svxlink_status {
	systemctl is-active svxlink
}

function svxlink_gpio_up {
	/usr/sbin/svxlink_gpio_up
	echo up
}

function svxlink_gpio_down {
	/usr/sbin/svxlink_gpio_down
	echo down
}


### SYSTEM FUNCTIONS ###
function system_reboot {
	shutdown -r now
}

function system_shutdown {
	shutdown -h now
}

function system_uptime {
	uptime
}

function system_user {
	whoami
}


### AUDIO FUNCTIONS ###
function audio_inputs {
	arecord -l
}

function audio_outputs {
	aplay -l
}

function audio_version {
	cat /proc/asound/version 2>&1
}


### AUDIO FUNCTIONS ###
function set_mixer {
	if [ -n "$3" ]; then
		amixer -c$3 set "$1" $2
	else
		amixer set "$1" $2
	fi
}

function alsamixer_backup {
	alsactl --file "$1" store
	chown www-data:www-data "$1"
}

function alsamixer_restore {
	alsactl --file "$1" restore
}


### NETWORK FUNCTIONS ###
function network_read {
	echo "Read Network Config for external parsing"
}

function network_write {
	echo "Write New Network Config"
}


### WEBSERVER FUNCTIONS ###
function www_stop {
	echo "Webserver / ORP GUI Stop"
	service nginx stop
}

function www_start {
	echo "Webserver / ORP GUI Start"
	service nginx start
}

function www_restart {
	echo "Webserver / ORP GUI Restart"
	service nginx restart
}

function www_disable {
	echo "Webserver / ORP GUI Disable"
	systemctl disable nginx
}

function www_enable {
	echo "Webserver / ORP GUI Enable"
	systemctl enable nginx
	service nginx restart
}



### INFO FUNCTIONS ###
function info_timezone {
	cat /etc/timezone
}

function info_cpu_type {
	cat /proc/cpuinfo | grep processor
}

function info_cpu_speed {
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
}

function info_cpu_load {
	{ head -n1 /proc/stat;sleep 0.2;head -n1 /proc/stat; } | awk '/^cpu /{u=$2-u;s=$4-s;i=$5-i;w=$6-w}END{print int(0.5+100*(u+s+w)/(u+s+i+w))}'
}

function info_cpu_temp {
	cat /sys/class/thermal/thermal_zone0/temp
}

function info_uptime {
	cat /proc/uptime
}

function info_memory_usage {
	cat /proc/meminfo
}

function info_disk_usage {
	df -T -l -BM -x tmpfs -x devtmpfs -x rootfs -x vfat
}

function info_os {
	uname -a
}

# TODO LIST
# Setting Timezone
# Expanding Filesystem


###############################################################################
# READ COMMAND LINE OPTIONS AND EXECUTE (Calls Functions Above)
###############################################################################

while :; do
    case $1 in
        svxlink)
			if [ "$2" == "start" ]; then svxlink_start
			elif [ "$2" == "stop" ]; then svxlink_stop
			elif [ "$2" == "restart" ]; then svxlink_restart
			elif [ "$2" == "status" ]; then svxlink_status
			elif [ "$2" == "enable" ]; then svxlink_enable
			elif [ "$2" == "disable" ]; then svxlink_disable
			elif [ "$2" == "gpio_up" ]; then svxlink_gpio_up
			elif [ "$2" == "gpio_down" ]; then svxlink_gpio_down
			else echo "INVALID OPTION"; echo "USAGE: orp_helper svxlink (start|stop|restart|status|enable|disable|gpio_up|gpio_down)"
			fi
			exit;;
        system)
			if [ "$2" == "stop" ]; then system_shutdown
			elif [ "$2" == "restart" ]; then system_reboot
			elif [ "$2" == "uptime" ]; then system_uptime
			elif [ "$2" == "user" ]; then system_user
			else echo "INVALID OPTION"; echo "USAGE: orp_helper system (stop|restart|uptime|user)"
			fi
			exit;;
        info)
			if [ "$2" == "timezone" ]; then info_timezone
			elif [ "$2" == "cpu_type" ]; then info_cpu_type
			elif [ "$2" == "cpu_speed" ]; then info_cpu_speed
			elif [ "$2" == "cpu_load" ]; then info_cpu_load
			elif [ "$2" == "cpu_temp" ]; then info_cpu_temp
			elif [ "$2" == "uptime" ]; then info_uptime
			elif [ "$2" == "memory_usage" ]; then info_memory_usage
			elif [ "$2" == "disk_usage" ]; then info_disk_usage
			elif [ "$2" == "os" ]; then info_os
			else echo "INVALID OPTION"; echo "USAGE: orp_helper info (timezone|cpu_type|cpu_speed|cpu_load|cpu_temp|uptime|memory_usage|disk_usage|os)"
			fi
			exit;;
#info_uptime
        www)
			if [ "$2" == "stop" ]; then www_stop
			elif [ "$2" == "start" ]; then www_start
			elif [ "$2" == "restart" ]; then www_restart
			elif [ "$2" == "disable" ]; then www_disable
			elif [ "$2" == "enable" ]; then www_enable
			else echo "INVALID OPTION"; echo "USAGE: orp_helper www (stop|start|restart|disable|enable)"
			fi
			exit;;
        audio)
			if [ "$2" == "inputs" ]; then audio_inputs
			elif [ "$2" == "outputs" ]; then audio_outputs
			elif [ "$2" == "version" ]; then audio_version
			else echo "INVALID OPTION"; echo "USAGE: orp_helper audio (inputs|outputs|version)"
			fi
			exit;;
        set_mixer)
			if [[ -n "$2" && -n "$3" && -n "$4" ]]; then set_mixer "$2" "$3" "$4"
			elif [[ -n "$2" && -n "$3" ]]; then set_mixer "$2" "$3"
			else echo "INVALID OPTION"; echo "USAGE: orp_helper set_mixer (setting) (value) [OPTIONAL: device]"
			fi
			exit;;
        alsa)
			if [ "$2" == "backup" ]; then alsamixer_backup "$3"
			elif [ "$2" == "restore" ]; then alsamixer_restore "$3"
			else echo "INVALID OPTION"; echo "USAGE: orp_helper alsa (backup|restore) [path]"
			fi
			exit;;
        network)
			if [ "$2" == "read" ]; then network_read
			elif [ "$2" == "write" ]; then network_write
			else echo "INVALID OPTION"; echo "USAGE: orp_helper network (read|write)"
			fi
			exit;;

        TEST)
			echo "Testing..."
			exit;;

        -h|-\?|--help|*)   # Display general help/info.
			display_help
			exit;;
    esac
done